### ISSUE TITLE
Epic: Build the Unbeatable Algorithm

### ISSUE THREAD

**Issue by IanDCarroll** [IanDCarroll/xox#20]
Make a clumsy first pass at creating an unbeatable algorithm

It should:
 - [x] win. else:
 - [x] block opponent's win. else:
 - [x] fork. else:
 - [x] block opponent's fork. else:
 - [x] occupy the center. else:
 - [x] occupy the opposite corner from an opponent's corner move. else:
 - [x] occupy a corner. else:
 - [x] occupy whatever sides remain.

It might be good to take a bottom-up approach, but likely we can build this modularly. Hopefully as we do so, we will discover how we can achieve this elegantly using the code we already have in place, especially in the observer class.

**Comment by IanDCarroll** [comment]
This algorithm may need simplification when it comes time to refactor. I'm getting the feeling that this could be achieved more eloquently. And more modularly. If I make it more decoupled, I could swap out different algorithms for different board types.
